/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2019-06-08 15:30:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1558703887773L));
    _jspx_dependants.put("jar:file:/D:/Giapha/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BTL_nhom2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" >\r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel='stylesheet' href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" >\r\n");
      out.write("\t<meta content=\"giapha, giatoc, tocpha, giaphả, giatộc, gia pha, gia toc, toc pha, gia phả, gia tộc, tộc phả,caygiapha, cay gia pha, cay gia dinh\" name=keywords>\r\n");
      out.write("\t<meta property=\"og:url\" content=\"http://www.vietnamgiapha.com\" />\r\n");
      out.write("\t<meta property=\"og:title\" content=\"Việt Nam Gia phả\" />\r\n");
      out.write("\t<meta property=\"og:description\" content=\"Nơi lưu trữ Gia phả của người Việt Nam\" />\r\n");
      out.write("\t<meta property=\"og:image\" content=\"exit.png\"/>\r\n");
      out.write("\t<meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("\t<title>Việt Nam Gia Phả</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-dark bg-dark navbar-expand-sm\">\r\n");
      out.write("\t  <div class=\"container\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t<img src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" alt=\"vietnamgiapha\"/>VIỆT NAM GIA PHẢ\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar-list-11\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t  <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbar-list-11\">\r\n");
      out.write("\t\t  <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t  <a class=\"nav-link\" href=\"#\" target=\"_blank\"><span class=\"glyphicon glyphicon-envelope\"></span> Download Phần Mềm</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t  <a class=\"nav-link\" href=\"#\" target=\"_blank\">Gia phả là gì</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t  <a class=\"nav-link\" href=\"#\" target=\"_self\">Hướng dẫn làm gia phả</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link\" href=\"Việt Nam Gia Phả.html\" onclick=\"logout()\">Đăng Xuất</a>\t\t\t\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- HEADER NAV - END -->\r\n");
      out.write("\t<nav class=\"navbar navbar-light bg-light navbar-expand-sm\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"name\" class=\"form-control\" placeholder=\"Tìm theo tên tộc họ\" aria-label=\"Tìm\" aria-describedby=\"button-addon2\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-info\" type=\"button\" onclick=\"loadGp()\" id=\"search_id\">Tìm kiếm</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"alert alert-warning\" role=\"alert\">\r\n");
      out.write("\t\t<p>Hiện tại bạn chưa có gia phả</p>\r\n");
      out.write("\t\t<p>Nếu muốn tạo mới gia phả\r\n");
      out.write("\t\t<a class=\"btn btn-sm btn-success\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\">Tạo mới tại đây</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container-fluid content-row\" id=\"list_gp\">\r\n");
      out.write("\t\t");

			out.print("<h1>haha</h1>");
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar navbar-dark bg-dark navbar-expand-sm\">\r\n");
      out.write("\t  <div class=\"container\">\r\n");
      out.write("\t\t<p style=\"color:white\">Dự án lưu trữ gia phả của người Việt, ra đời từ năm 2003 đến nay</p>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("    <script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("    <script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <script src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction ucFirstAllWords( str )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar pieces = str.split(\" \");\r\n");
      out.write("\t\tfor ( var i = 0; i < pieces.length; i++ )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar j = pieces[i].charAt(0).toUpperCase();\r\n");
      out.write("\t\t\tpieces[i] = j + pieces[i].substr(1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn pieces.join(\" \");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#search_id').keypress(function(event){\r\n");
      out.write("\t\t\tvar keycode = (event.keyCode ? event.keyCode : event.which);\r\n");
      out.write("\t\t\tif(keycode == '13' ||keycode ==13){\r\n");
      out.write("\t\t\t   loadGp();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$( \"#username\" )\r\n");
      out.write("\t\t  .blur(function() {\r\n");
      out.write("\t\t\t  $( \"#username\" ).val( \"\"+$( \"#username\" ).val().trim().toLowerCase() );\r\n");
      out.write("\t\t\t  checku();\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t$( \"#email\" )\r\n");
      out.write("\t\t  .blur(function() {\r\n");
      out.write("\t\t\t  checke();\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t$( \"#loginid\" )\r\n");
      out.write("\t\t  .blur(function() {\r\n");
      out.write("\t\t\t  $( \"#loginid\" ).val( \"\"+$( \"#loginid\" ).val().trim().toLowerCase() );\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t$( \"#fullname\" )\r\n");
      out.write("\t\t  .blur(function() {\r\n");
      out.write("\t\t\t  $( \"#fullname\" ).val( \"\"+ ucFirstAllWords( $( \"#fullname\" ).val().trim()) );\r\n");
      out.write("\t\t  });\r\n");
      out.write("loadGp();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadGp(){\r\n");
      out.write("\t\t$(\"#list_gp\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\">');\r\n");
      out.write("\t\tvar name = $(\"#name\").val();\r\n");
      out.write("\t\tvar url = \"http://localhost:8080/adv/parentage/view?name=\"+name+\"\";\r\n");
      out.write("\t\tvar request;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (window.XMLHttpRequest) {\r\n");
      out.write("            request = new XMLHttpRequest();\r\n");
      out.write("        } else if (window.ActiveXObject) {\r\n");
      out.write("            request = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        try {\r\n");
      out.write("            request.onreadystatechange = getInfo;\r\n");
      out.write("            request.open(\"GET\", url, true);\r\n");
      out.write("            request.send();\r\n");
      out.write("        } catch (e) {\r\n");
      out.write("            alert(\"Unable to connect to server\");\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \tfunction getInfo() {\r\n");
      out.write("        \tif (request.readyState == 4) {\r\n");
      out.write("        \t    var val = request.responseText;\r\n");
      out.write("        \t    $(\"#list_gp\").html(val);\r\n");
      out.write("       \t \t}\r\n");
      out.write("  \t  \t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction forget_password(){\r\n");
      out.write("\t\talert(\"Chỗ ID, bạn nhập vào email của bạn.\\nSau đó hệ thống sẽ tự gửi về đó password mới.\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar username = $(\"#loginid\").val().trim();\r\n");
      out.write("\t\tvar error = 0;\r\n");
      out.write("\t\tif( username.length<2 ){\r\n");
      out.write("\t\t\t$('[name=\"loginid\"]').parent().parent().addClass('has-error');\r\n");
      out.write("\t\t\t$('[name=\"loginid\"]').next().text(\"Nhập vào [loginid] để lấy lại password\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tif( isEmail(username)==false ){\r\n");
      out.write("\t\t\t\t$('[name=\"loginid\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t\t$('[name=\"loginid\"]').next().text(\"hoặc nhập vào [email] để lấy lại password\");\r\n");
      out.write("\t\t\t\terror = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$('[name=\"loginid\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t\t$('[name=\"loginid\"]').next().text(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(error ===1 ){\r\n");
      out.write("\t\t\t$(\"#login_msg\").html('Có lỗi');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#login_msg\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\"/>');\r\n");
      out.write("\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tusername:username,\r\n");
      out.write("\t\t\t\tfunc:\"forget\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\talert(data.reason);\r\n");
      out.write("\t\t\t\t$(\"#pass\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#login_msg\").html('');\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction open_login()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$('#modal_form_register').modal('hide'); // show bootstrap modal\r\n");
      out.write("\t\t$('#form')[0].reset(); // reset form on modals\r\n");
      out.write("\t\t$('.form-group').removeClass('has-error'); // clear error class\r\n");
      out.write("\t\t$('#modal_form_login').modal('show'); // show bootstrap modal\r\n");
      out.write("\t\t$(\"#loginid\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logout()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: {func:\"logout\"},\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\tif( data.status=='ok'){\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction isEmail(email) {\r\n");
      out.write("\t\tvar regex = /^([a-zA-Z0-9_.+-])+\\@(([a-zA-Z0-9-])+\\.)+([a-zA-Z0-9]{2,4})+$/;\r\n");
      out.write("\t\treturn regex.test(email);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction open_register()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$('#modal_form_login').modal('hide'); // show bootstrap modal\r\n");
      out.write("\t\t$('.form-group').removeClass('has-error'); // clear error class\r\n");
      out.write("\t\t$('#modal_form_register').modal('show'); // show bootstrap modal\r\n");
      out.write("\t\t$(\"#username\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction login()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$(\"#login_msg\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\"/>');\r\n");
      out.write("\t\tvar username = $(\"#loginid\").val().trim();\r\n");
      out.write("\t\tvar password = $(\"#pass\").val().trim();\r\n");
      out.write("\t\tvar error = 0;\r\n");
      out.write("\t\tif( username.length<5 ){\r\n");
      out.write("\t\t\t$('[name=\"loginid\"]').parent().parent().addClass('has-error');\r\n");
      out.write("\t\t\t$('[name=\"loginid\"]').next().text(\"[loginid] không để trống, >5 ký tự\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( password.length<5 ){\r\n");
      out.write("\t\t\t$('[name=\"pass\"]').parent().parent().addClass('has-error');\r\n");
      out.write("\t\t\t$('[name=\"pass\"]').next().text(\"[pass] không để trống, >=8 ký tự\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(error ===1 ){\r\n");
      out.write("\t\t\t$(\"#login_msg\").html('Có lỗi');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar sendInfo = {\r\n");
      out.write("\t\t\tpassword: password,\r\n");
      out.write("\t\t\tusername:username,\r\n");
      out.write("\t\t\tfunc:\"login\",\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: sendInfo,\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\t$(\"#login_msg\").html(data.reason);\r\n");
      out.write("\t\t\t\tif( data.status=='ok'){\r\n");
      out.write("\t\t\t\t\t$('#modal_form_login').modal('hide'); // show bootstrap modal\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t$(\"#login_msg\").html('Có lỗi đăng ký thành viên');\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\tvar error = 0;\r\n");
      out.write("\tfunction register()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//console.log(\"Đang ký\");\r\n");
      out.write("\t\tvar username = $(\"#username\").val().trim();\r\n");
      out.write("\t\tvar password = $(\"#password\").val().trim();\r\n");
      out.write("\t\tvar email = $(\"#email\").val().trim();\r\n");
      out.write("\t\tvar fullname = $(\"#fullname\").val().trim();\r\n");
      out.write("\t\t//\r\n");
      out.write("\t\tif( error > 1 ){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( username.length<5 ){\r\n");
      out.write("\t\t\t$('[name=\"username\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t$('[name=\"username\"]').next().text(\"[username] không để trống, >5 ký tự\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"username\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"username\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( password.length<8 ){\r\n");
      out.write("\t\t\t$('[name=\"password\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t$('[name=\"password\"]').next().text(\"[password] không để trống, >=8 ký tự\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"password\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"password\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( isEmail(email)==false ){\r\n");
      out.write("\t\t\t$('[name=\"email\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t$('[name=\"email\"]').next().text(\"[email] phải đúng\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"email\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"email\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif( fullname.length<5 ){\r\n");
      out.write("\t\t\t$('[name=\"fullname\"]').parent().parent().addClass('has-error');\r\n");
      out.write("\t\t\t$('[name=\"fullname\"]').next().text(\"[fullname] không để trống, 10 ký tự\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"fullname\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"fullname\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(error ==1 ){\r\n");
      out.write("\t\t\t$(\"#register_msg\").html('Có lỗi nhập thông tin');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#register_msg\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f12(_jspx_page_context))
        return;
      out.write("\"/>');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sendInfo = {\r\n");
      out.write("\t\t\tpassword: password,\r\n");
      out.write("\t\t\tusername:username,\r\n");
      out.write("\t\t\temail:email,\r\n");
      out.write("\t\t\tfullname:fullname,\r\n");
      out.write("\t\t\tfunc:\"register\",\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: sendInfo,\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\t$(\"#register_msg\").html(data.reason);\r\n");
      out.write("\t\t\t\tif( data.status=='ok'){\r\n");
      out.write("\t\t\t\t\t$('#modal_form_register').modal('hide'); // show bootstrap modal\r\n");
      out.write("\t\t\t\t\topen_login();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t$(\"#register_msg\").html('Có lỗi đăng ký thành viên');\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checke()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//console.log(\"Đang ký\");\r\n");
      out.write("\t\t$(\"#register_msg\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f13(_jspx_page_context))
        return;
      out.write("\"/>');\r\n");
      out.write("\t\tvar email = $(\"#email\").val().trim();\r\n");
      out.write("\t\tif( isEmail(email)==false ){\r\n");
      out.write("\t\t\t$('[name=\"email\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t$('[name=\"email\"]').next().text(\"[email] phải đúng\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"email\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"email\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(error ==1 ){\r\n");
      out.write("\t\t\t$(\"#register_msg\").html('Có lỗi nhập thông tin');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar sendInfo = {\r\n");
      out.write("\t\t\temail:email,\r\n");
      out.write("\t\t\tfunc:\"checke\",\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: sendInfo,\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\tif( data.status>0){\r\n");
      out.write("\t\t\t\t\t$('[name=\"email\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t\t\t$('[name=\"email\"]').next().text(\"[email] có lỗi. Email đã có người dùng\");\r\n");
      out.write("\t\t\t\t\terror = 2;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t$('[name=\"email\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t\t\t$('[name=\"email\"]').next().text(\"\");\r\n");
      out.write("\t\t\t\t\terror = 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#register_msg\").html('');\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checku()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//console.log(\"Đang ký\");\r\n");
      out.write("\t\t$(\"#register_msg\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f14(_jspx_page_context))
        return;
      out.write("\"/>');\r\n");
      out.write("\t\tvar username = $(\"#username\").val().trim();\r\n");
      out.write("\t\tvar email = $(\"#email\").val().trim();\r\n");
      out.write("\t\tif( username.length<5 || username.indexOf(\" \")>-1 ){\r\n");
      out.write("\t\t\t$('[name=\"username\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t$('[name=\"username\"]').next().text(\"[username] không để trống, >5 ký tự\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"username\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"username\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(error ==1 ){\r\n");
      out.write("\t\t\t$(\"#register_msg\").html('Có lỗi nhập thông tin');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar sendInfo = {\r\n");
      out.write("\t\t\tusername:username,\r\n");
      out.write("\t\t\tfunc:\"checku\",\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: sendInfo,\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\tif( data.status>0){\r\n");
      out.write("\t\t\t\t\t$('[name=\"username\"]').parent().parent().addClass('error');\r\n");
      out.write("\t\t\t\t\t$('[name=\"username\"]').next().text(\"[username] đã có người chọn\");\r\n");
      out.write("\t\t\t\t\terror = 3;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t$('[name=\"username\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t\t\t$('[name=\"username\"]').next().text(\"\");\r\n");
      out.write("\t\t\t\t\terror = 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#register_msg\").html('');\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction open_reset_password(code){\r\n");
      out.write("\t\t$(\"#reset_code\").val(\"\"+code);\r\n");
      out.write("\t\t$('#modal_form_reset_password').modal('show');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction reset_password()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar code = $(\"#reset_code\").val().trim();\r\n");
      out.write("\t\tvar reset_pass = $(\"#reset_pass\").val().trim();\r\n");
      out.write("\t\tvar reset_pass1 = $(\"#reset_pass1\").val().trim();\r\n");
      out.write("\t\tvar error = 0;\r\n");
      out.write("\t\tif( reset_pass!=reset_pass1 ){\r\n");
      out.write("\t\t\t$('[name=\"reset_pass1\"]').parent().parent().addClass('has-error');\r\n");
      out.write("\t\t\t$('[name=\"reset_pass1\"]').next().text(\"Phải nhập lại password 2 lần giống nhau\");\r\n");
      out.write("\t\t\terror = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('[name=\"reset_pass1\"]').parent().parent().attr('class','').addClass('form-group');\r\n");
      out.write("\t\t\t$('[name=\"reset_pass1\"]').next().text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(error ===1 ){\r\n");
      out.write("\t\t\t$(\"#reset_msg\").html('Có lỗi');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#reset_msg\").html('<img src=\"");
      if (_jspx_meth_c_005furl_005f15(_jspx_page_context))
        return;
      out.write("\"/>');\r\n");
      out.write("\t\tvar sendInfo = {\r\n");
      out.write("\t\t\tcode: code,\r\n");
      out.write("\t\t\treset_pass:reset_pass,\r\n");
      out.write("\t\t\treset_pass1:reset_pass1,\r\n");
      out.write("\t\t\tfunc:\"reset_password\",\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// ajax\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\turl : \"login.php\",\r\n");
      out.write("            type : \"POST\",\r\n");
      out.write("\t\t\tdata: sendInfo,\r\n");
      out.write("            success: function(datastr) {\r\n");
      out.write("\t\t\t\tdata = JSON.parse(datastr);\r\n");
      out.write("\t\t\t\t$(\"#reset_msg\").html(data.reason);\r\n");
      out.write("\t\t\t\tif( data.status=='ok'){\r\n");
      out.write("\t\t\t\t\talert(\"Thành công: \" + data.reason);\r\n");
      out.write("\t\t\t\t\t$('#modal_form_reset_password').modal('hide'); // show bootstrap modal\r\n");
      out.write("\t\t\t\t\t$('#modal_form_login').modal('show'); // show bootstrap modal\r\n");
      out.write("\t\t\t\t\twindow.location.href = \"http://www.vietnamgiapha.com/m\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert(\"Có lỗi: \" + data.reason);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t$(\"#reset_msg\").html('Có lỗi');\r\n");
      out.write("\t\t\t\talert('Error '+ textStatus);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Bootstrap modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"modal_form_login\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"largeModalLabel\">ĐĂNG NHẬP</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                <div class=\"modal-body form\">\r\n");
      out.write("\t\t\t\t\t<div id=\"login_msg\"></div>\r\n");
      out.write("                    <form id=\"form\" data-parsley-validate=\"\" class=\"form-horizontal form-label-left\" novalidate=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"loginid\" id=\"loginid\" class=\"form-control\" placeholder=\"ID\" required autofocus>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"pass\" id=\"pass\" class=\"form-control\" value=\"\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-primary btn-block text-uppercase\" onclick=\"login()\" >ĐĂNG NHẬP</button>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"my-4\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-info btn-block text-uppercase\" onclick=\"open_register()\" >Đăng ký mới</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-info btn-block text-uppercase\" onclick=\"forget_password()\" >Quên password</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-lg btn-info btn-block text-uppercase\" data-dismiss=\"modal\" type=\"button\"> Bỏ qua</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- /.modal-content -->\r\n");
      out.write("        </div><!-- /.modal-dialog -->\r\n");
      out.write("    </div><!-- /.modal -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"modal fade\" id=\"modal_form_register\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"largeModalLabel\">ĐĂNG KÝ THÀNH VIÊN</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                <div class=\"modal-body form\">\r\n");
      out.write("\t\t\t\t\t<div id=\"register_msg\"></div>\r\n");
      out.write("                    <form id=\"form1\" data-parsley-validate=\"\" class=\"form-horizontal form-label-left\" novalidate=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" id=\"username\" class=\"form-control\" placeholder=\"Email hoặc ID\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"password\" id=\"password\" class=\"form-control\" value=\"\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" id=\"email\" class=\"form-control\" placeholder=\"Email của bạn.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"fullname\" id=\"fullname\" class=\"form-control\" value=\"\" placeholder=\"Tên đầy đủ\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-primary btn-block text-uppercase\" onclick=\"register()\" >Đăng ký mới</button>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"my-4\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-info btn-block text-uppercase\" onclick=\"open_login()\" >Login</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-lg btn-info btn-block text-uppercase\" data-dismiss=\"modal\" type=\"button\"> Bỏ qua</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- /.modal-content -->\r\n");
      out.write("        </div><!-- /.modal-dialog -->\r\n");
      out.write("    </div><!-- /.modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"modal_form_reset_password\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"largeModalLabel\">RESET PASSWORD</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                <div class=\"modal-body form\">\r\n");
      out.write("\t\t\t\t\t<div id=\"login_msg\"></div>\r\n");
      out.write("                    <form id=\"form\" data-parsley-validate=\"\" class=\"form-horizontal form-label-left\" novalidate=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"reset_code\" id=\"reset_code\" class=\"form-control\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"reset_pass\" id=\"reset_pass\" class=\"form-control\" value=\"\" placeholder=\"Password mới\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"reset_pass1\" id=\"reset_pass1\" class=\"form-control\" value=\"\" placeholder=\"Password nhập lại\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-primary btn-block text-uppercase\" onclick=\"reset_password()\" ><i class=\"fa fa-sign-in\"></i> Lưu password mới</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- /.modal-content -->\r\n");
      out.write("        </div><!-- /.modal-dialog -->\r\n");
      out.write("    </div><!-- /.modal -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/admin/manager.jsp(10,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/adcss/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/admin/manager.jsp(11,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/adcss/bootstrap.icon-large.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/admin/manager.jsp(12,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/adcss/all.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/admin/manager.jsp(24,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("#");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/admin/manager.jsp(25,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/adimgs/exit.png");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/admin/manager.jsp(63,42) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/individual/ae");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/admin/manager.jsp(77,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/adjs/js/jquery-3.2.1.min.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/admin/manager.jsp(78,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/adjs/js/popper.min.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/admin/manager.jsp(79,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/adjs/js/bootstrap.min.js");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/admin/manager.jsp(120,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/adimgs/loading1.gif");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /views/admin/manager.jsp(172,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/adjs/loading1.gif");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /views/admin/manager.jsp(234,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/adimgs/loading1.gif");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent(null);
      // /views/admin/manager.jsp(329,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/adimgs/loading1.gif");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f13 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f13_reused = false;
    try {
      _jspx_th_c_005furl_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f13.setParent(null);
      // /views/admin/manager.jsp(360,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f13.setValue("/adimgs/loading1.gif");
      int _jspx_eval_c_005furl_005f13 = _jspx_th_c_005furl_005f13.doStartTag();
      if (_jspx_th_c_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f13);
      _jspx_th_c_005furl_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f13, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f14 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f14_reused = false;
    try {
      _jspx_th_c_005furl_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f14.setParent(null);
      // /views/admin/manager.jsp(406,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f14.setValue("/adimgs/loading1.gif");
      int _jspx_eval_c_005furl_005f14 = _jspx_th_c_005furl_005f14.doStartTag();
      if (_jspx_th_c_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f14);
      _jspx_th_c_005furl_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f14, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f15 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f15_reused = false;
    try {
      _jspx_th_c_005furl_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f15.setParent(null);
      // /views/admin/manager.jsp(473,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f15.setValue("/adjs/loading1.gif");
      int _jspx_eval_c_005furl_005f15 = _jspx_th_c_005furl_005f15.doStartTag();
      if (_jspx_th_c_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f15);
      _jspx_th_c_005furl_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f15, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f15_reused);
    }
    return false;
  }
}
